### ISSUE TITLE
Color not saved properly

### ISSUE THREAD

**Issue by CollinChaffin** [mitchcapper/KPFloatingPanel#7]
Hi is this still being actively developed?  I may try to do a pull surprised no one else has opened an issue I guess nobody has ever tried to change the button color?  I've tried on 2 machines it changes fine but upon closing keepass and reopening, the background color has reset to white will not hold color.

**Comment by mitchcapper** [comment]
Ha! I guess not. That feature pre-dates when I took the project over, and I never used it.  On mine it actually crashes the plugin on launch if you change the color I will try to get a fix pushed up today.

**Comment by mitchcapper** [comment]
turns out known colors would work (colors that windows had a name for) just not random colors.  All fixed.

**Comment by CollinChaffin** [comment]
Awesome!  Any chance you can recompile a new release?  I still have the other open issue for the life of me cannot get the keybinding to do hotkeys trying on 2 different systems are you sure it is supposed to be working properly on this release?  Bear in mind, there is only ONE release here from one commit so is it possible we are all running a plgx release that has bugs?

**Comment by mitchcapper** [comment]
Yeah will at some point.  I don't use the PLGX itself actually so I can't confirm if the key bindings are broke. I could download it with a fresh copy of keepass.  Keep in mind compiling the PLGX is pretty easy if you wanted to do so for yourself.

**Comment by mitchcapper** [comment]
Just downloaded 2.35 of KP portable, placed the PLGX in the same folder.  Ran keepass assigned control + shift + R as the key sequence.  Hit and held control, then held shift, then hit R (all with left hand) and it popped up the box to search.  Do you have any other app that might be intercepting key strokes?
